package:
  name: aerospike-7
  version: 7.2.0.1
  epoch: 0
  description: Aerospike Database Server - flash-optimized, in-memory, nosql database
  copyright:
    - license: AGPL-3.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - coreutils
      - gmp-dev
      - libtool
      - openssl-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aerospike/aerospike-server
      tag: ${{package.version}}
      expected-commit: 12df0c5b9553a2c4291d438ecc873b5d424a4c06

  - runs: git submodule update --init

  - runs: |
      # There's some OS detection that doesn't know about wolfi and gets the wrong path
      sed -i 's|ABSL_LIB_DIR = $(ABSL)/installation/lib$|ABSL_LIB_DIR = $(ABSL)/installation/lib64|g' make_in/Makefile.vars

      # Fix some warnings
      sed -i 's|COMMON_CFLAGS += -Wno-address-of-packed-member|COMMON_CFLAGS += -Wno-address-of-packed-member -Wno-use-after-free|g' make_in/Makefile.in

      git diff

  - runs: |
      export CFLAGS="-Wno-address-of-packed-member -Wno-use-after-free"
      export CXXFLAGS="$CFLAGS"
      export CPPFLAGS="$CFLAGS"
      make -j$(nproc)
      make source

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin ${{targets.destdir}}/usr/share
      tar -C ${{targets.destdir}}/usr/share -xf pkg/packages/aerospike-server-community-${{package.version}}.src.tar.bz2

      ln -sf /usr/share/aerospike/bin/asd ${{targets.destdir}}/usr/bin/asd
      ln -sf /usr/share/aerospike/bin/aerospike ${{targets.destdir}}/usr/bin/aerospike

update:
  enabled: true
  github:
    identifier: aerospike/aerospike-server
    tag-filter: 7.
