package:
  name: az
  version: 2.65.0
  epoch: 0
  description: Azure CLI
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.11-pip
      - python-3.11
      - python-3.11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-cli/
      tag: azure-cli-${{package.version}}
      expected-commit: a0acfb32a5966fac72f54d25639ebc5fbd53a509

  - name: Python Build
    runs: |
      pip install wheel
      cd src/azure-cli
      python setup.py bdist_wheel
      cd ../azure-cli-core
      python setup.py bdist_wheel

  - runs: |
      # Setup the virtualenv
      python -m venv .venv
      # Bump pip to patch a CVE
      .venv/bin/pip install --upgrade pip==23.3.2
      .venv/bin/pip install --upgrade setuptools==70.0.0

  - runs: |
      .venv/bin/pip install --no-compile src/azure-cli/dist/*.whl src/azure-cli-core/dist/*.whl

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/az
      mv .venv ${{targets.destdir}}/usr/share/az/

      # edit the venv paths
      sed -i "s|/home/build|/usr/share/az|g" ${{targets.destdir}}/usr/share/az/.venv/bin/*

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      ln -s /usr/share/az/.venv/bin/az ${{targets.destdir}}/usr/bin/az

  - uses: strip

update:
  enabled: true
  github:
    identifier: Azure/azure-cli
    strip-prefix: azure-cli-

test:
  pipeline:
    - runs: |
        az --version
        az -h
