package:
  name: buck2
  # When bumping the version, you also need to retrieve the specific nightly
  # version of rust that is compatible. To determine, go to the following URL:
  # - https://github.com/facebook/buck2/blob/<VERSION>/HACKING.md
  # Get the version, and update vars.rust-version below.
  version: 20241001
  epoch: 1
  description: "Build system, successor to Buck"
  copyright:
    - license: MIT
  resources:
    cpu: 10
    memory: 16Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rustup
      - wolfi-base

vars:
  rust-version: nightly-2024-06-08

var-transforms:
  - from: ${{package.version}}
    match: (\d{4})(\d{2})(\d{2})
    replace: $1-$2-$3
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facebook/buck2
      expected-commit: 66770ab8db7f9545a0772328e28e740717a6eb72
      tag: ${{vars.mangled-package-version}}

  - uses: patch
    with:
      patches: GHSA-hc92-9h3m-c39j.patch

  - name: Configure and build
    runs: |
      # This build requires a specific version of rust nightly.
      # Be sure to check docs when bumping to more recent commits.
      rustup install ${{vars.rust-version}}

      # This is a bit of a hack, but it's the easiest way to get the right version of rustc and cargo in the path.
      export PATH="$HOME/.rustup/toolchains/${{vars.rust-version}}-${{host.triplet.rust}}/bin:$PATH"
      mkdir -p ${{targets.destdir}}/usr/bin/
      cd app/buck2

      cargo auditable build --release
      mv ../../target/release/buck2 ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  manual: true
  ignore-regex-patterns:
    - 'latest'
  github:
    identifier: facebook/buck2
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        buck2 --version
        buck2 --help
