package:
  name: chrony
  version: 4.6.1
  epoch: 0
  description: NTP client and server programs
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - asciidoctor
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - gnutls-dev
      - libcap-dev
      - libseccomp-dev
      - nettle-dev
      - texinfo
      - wolfi-baselayout
  accounts:
    groups:
      - groupname: chrony
        gid: 10000
    users:
      - username: chrony
        uid: 10000

pipeline:
  - uses: fetch
    with:
      expected-sha512: 646ae08f2587366236796f2399d8ab3eb570979e0d82f5d13f5cec49939054c876cc93dc20c8d38e105fd3500e1720d05a223a15076783cd882d0de43afd9c7e
      uri: "https://chrony-project.org/releases/chrony-${{package.version}}.tar.gz"

  - runs: |
      mkdir -p pps-tools/sys
      cp ./timepps.h pps-tools/sys/

  - runs: |
      CPPFLAGS="$CPPFLAGS -I./pps-tools/" \
      CFLAGS="$CFLAGS -flto=auto" \
      ./configure \
      	--prefix=/usr \
      	--mandir=/usr/share/man \
      	--sysconfdir=/etc/chrony \
      	--chronyrundir=/run/chrony \
      	--disable-readline \
      	--with-user=chrony \
      	--with-sendmail=/usr/sbin/sendmail \
      	--enable-ntp-signd \
      	--enable-scfilter
      make all docs

  - runs: |
      make DESTDIR="${{targets.destdir}}" install

      mkdir -p "${{targets.destdir}}"/etc/logrotate.d
      install -Dm644 examples/chrony.logrotate "${{targets.destdir}}"/etc/logrotate.d/chrony
      mkdir -p "${{targets.destdir}}"/usr/share/doc/chrony
      install -m644 examples/*.example "${{targets.destdir}}"/usr/share/doc/chrony/
      install -Dm755 ./chronyd.initd "${{targets.destdir}}"/etc/init.d/chronyd
      install -Dm644 ./chronyd.confd "${{targets.destdir}}"/etc/conf.d/chronyd

      install -dm2750 -g wheel "${{targets.destdir}}"/var/log/chrony

      mkdir -p "${{targets.destdir}}"/var/lib/chrony \
           "${{targets.destdir}}"/etc/chrony \
           "${{targets.destdir}}"/var/run/chrony

      # chrony.drift must be writable by chrony user
      chown ${{package.name}}:${{package.name}} "${{targets.destdir}}"/etc/chrony
      install -m644 ./chrony.conf "${{targets.destdir}}"/etc/chrony/chrony.conf
      chown root:root "${{targets.destdir}}"/etc/chrony/*
      chown ${{package.name}}:${{package.name}} "${{targets.destdir}}"/var/lib/chrony
      touch "${{targets.destdir}}"/var/lib/chrony/chrony.drift

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 8810

test:
  environment:
    contents:
      packages:
        - procps
        - shadow
  pipeline:
    - name: "Check chrony version"
      runs: |
        chronyd --version
        chronyc --version
        chronyc --help
        chronyd --help
    - name: "Setup chrony user and group"
      runs: |
        groupadd -g 10000 chrony
        useradd -u 10000 -g chrony -d /var/lib/chrony -s /sbin/nologin chrony
        chown -R chrony:chrony /var/lib/chrony /etc/chrony
        chown root:wheel /var/log/chrony
        chmod 2750 /var/log/chrony
    - name: "Test chronyd configuration parsing and system clock check"
      runs: |
        cat > test.conf << EOF
        pool pool.ntp.org iburst
        EOF
        chronyd -Q -f test.conf 2>&1 | grep -E "System clock wrong by -?[0-9]+\.[0-9]+ seconds \(ignored\)"
