package:
  name: cosign
  version: 2.4.1
  epoch: 0
  description: Container Signing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9a4cfe1aae777984c07ce373d97a65428bbff734
      repository: https://github.com/sigstore/cosign
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5+incompatible
      replaces: github.com/docker/docker=github.com/docker/docker@v26.1.5+incompatible

  - uses: go/build
    with:
      ldflags: -s -w -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
      output: cosign
      packages: ./cmd/cosign

  - uses: strip

test:
  environment:
    contents:
      packages:
        - jq
        - busybox
  pipeline:
    - name: Verify Cosign installation
      runs: |
        cosign version || exit 1
        cosign --help
    - name: Get an attestation and test
      runs: |
        arch=$(uname -m | sed -e "s/x86_64/amd64/" -e "s/aarch64/arm64/")
        cosign download attestation --platform=linux/$arch \
        --predicate-type=https://spdx.dev/Document \
        chainguard/curl | jq -r .payload | base64 -d | jq .predicate

update:
  enabled: true
  github:
    identifier: sigstore/cosign
    strip-prefix: v
