package:
  name: curl
  version: 8.9.1
  epoch: 2
  description: "URL retrieval utility and library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpsl-dev
      - nghttp2-dev
      - openssl-dev
      - perl
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://curl.se/download/curl-${{package.version}}.tar.xz
      expected-sha256: f292f6cc051d5bbabf725ef85d432dfeacc8711dd717ea97612ae590643801e5

  - uses: autoconf/configure
    with:
      # https://everything.curl.dev/build/deps#libpsl
      opts: |
        --enable-ipv6 \
        --enable-unix-sockets \
        --with-openssl \
        --without-rustls \
        --with-nghttp2 \
        --with-pic \
        --disable-ldap \
        --disable-ntlm \
        --without-libssh2 \
        --with-libpsl

  - uses: autoconf/make
    with:
      opts: CPPFLAGS="$CPPFLAGS -DOPENSSL_NO_ENGINE"

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "curl-dev"
    description: "headers for libcurl"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - brotli-dev        
        - libpsl-dev
        - nghttp2-dev
        - openssl-dev

  - name: "curl-doc"
    description: "documentation for curl"
    pipeline:
      - uses: split/manpages

  - name: "libcurl-openssl4"
    description: "curl library (openssl backend)"
    dependencies:
      # raise the priority here so this beats rustls
      # TODO: revert this to "5" once rustls is fixed.
      provider-priority: 15
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libcurl.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/curl
    strip-prefix: curl-

test:
  pipeline:
    - runs: |
        curl --version
        curl -v https://example.com
        curl -s --output /dev/null --compressed https://aur.archlinux.org
