package:
  name: dagger
  version: 0.13.4
  epoch: 0
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: b35757b05ff35243483dbc6ab0a3cf9a95b41b59

  - uses: go/build
    with:
      ldflags: -s -w  -X github.com/dagger/dagger/engine.Version=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
        dagger --help
