package:
  name: dpkg
  version: 1.22.11
  epoch: 0
  description: "The Debian Package Manager"
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - gnutar # dpkg specifically needs GNU tar instead of bsdtar
      - libmd-dev
      - patch
      - perl
      - wolfi-base
      - xz
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: http://ftp.de.debian.org/debian/pool/main/d/dpkg/dpkg_${{package.version}}.tar.xz
      expected-sha256: f318eb949b8e7ecd802b17b1a7e7cf4b17094c9577e1060653e9b838cdd31d80

  - runs: |
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --with-libz \
        --with-libbz2 \
        --disable-dselect \
        --disable-start-stop-daemon \
        --disable-nls

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "dpkg-dev"
    description: "headers for dpkg"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv "${{targets.destdir}}"/usr/bin/dpkg-architecture \
            "${{targets.destdir}}"/usr/bin/dpkg-buildpackage \
            "${{targets.destdir}}"/usr/bin/dpkg-checkbuilddeps \
            "${{targets.destdir}}"/usr/bin/dpkg-distaddfile \
            "${{targets.destdir}}"/usr/bin/dpkg-genchanges \
            "${{targets.destdir}}"/usr/bin/dpkg-gencontrol \
            "${{targets.destdir}}"/usr/bin/dpkg-gensymbols \
            "${{targets.destdir}}"/usr/bin/dpkg-name \
            "${{targets.destdir}}"/usr/bin/dpkg-scanpackages \
            "${{targets.destdir}}"/usr/bin/dpkg-scansources \
            "${{targets.destdir}}"/usr/bin/dpkg-shlibdeps \
            "${{targets.destdir}}"/usr/bin/dpkg-source \
            "${{targets.destdir}}"/usr/bin/dpkg-vendor \
            "${{targets.subpkgdir}}"/usr/bin/

          mkdir -p "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/perl* "${{targets.subpkgdir}}"/usr/share/
    dependencies:
      runtime:
        - dpkg
    test:
      pipeline:
        - runs: |
            dpkg-architecture --version
            dpkg-architecture --help
            dpkg-buildpackage --version
            dpkg-buildpackage --help
            dpkg-checkbuilddeps --version
            dpkg-checkbuilddeps --help
            dpkg-distaddfile --version
            dpkg-distaddfile --help
            dpkg-genchanges --version
            dpkg-genchanges --help
            dpkg-gencontrol --version
            dpkg-gencontrol --help
            dpkg-gensymbols --version
            dpkg-gensymbols --help
            dpkg-name --version
            dpkg-name --help
            dpkg-scanpackages --version
            dpkg-scanpackages --help
            dpkg-scansources --version
            dpkg-scansources --help
            dpkg-shlibdeps --version
            dpkg-shlibdeps --help
            dpkg-source --version
            dpkg-source --help
            dpkg-vendor --version
            dpkg-vendor --help

update:
  enabled: true
  release-monitor:
    identifier: 8127

test:
  environment:
    contents:
      packages:
        - perl
        - bzip2
        - libmd
        - zlib
        - gnutar
        - xz
        - build-base
  pipeline:
    - name: Create a sample Debian package
      runs: |
        mkdir -p test/data
        echo "brew" > test/data/homebrew.txt
        mkdir -p test/DEBIAN
        arch=$(uname -m | sed -e "s/x86_64/amd64/" -e "s/aarch64/arm64/")
        cat <<EOF > test/DEBIAN/control
        Package: test
        Version: 1.40.99
        Architecture: $arch
        Description: I am a test
        Maintainer: Dpkg Developers <test@test.org>

        EOF
        dpkg-deb --build test test.deb
        [ -f test.deb ] || exit 1
        dpkg --version
        dpkg --help
        dpkg-deb --version
        dpkg-deb --help
        dpkg-divert --version
        dpkg-divert --help
        dpkg-maintscript-helper --version
        dpkg-maintscript-helper --help
        dpkg-query --version
        dpkg-query --help
        dpkg-realpath --version
        dpkg-realpath --help
        dpkg-split --version
        dpkg-split --help
        dpkg-statoverride --version
        dpkg-statoverride --help
        dpkg-trigger --version
        dpkg-trigger --help
        update-alternatives --version
        update-alternatives --help
    - name: Extract the Debian package
      runs: |
        rm -rf test
        dpkg-deb --extract test.deb test
        [ -f test/data/homebrew.txt ] || exit 1
