package:
  name: falco
  version: 0.39.1 # on update check if we can remove the 'Patch falcosecurity-libs' pipeline below if https://github.com/falcosecurity/libs/pull/2079 is merged
  epoch: 0
  description: Cloud Native Runtime Security
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - falco-rules
      - falcoctl

vars:
  llvm-vers: 19

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - bash
      - binutils
      - bpftool
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - clang-${{vars.llvm-vers}}-dev
      - cmake
      - cpp-httplib
      - curl-dev
      - cxxopts-dev
      - elfutils-dev
      - git
      - grpc-dev
      - icu-dev
      - jq-dev
      - jsoncpp-dev
      - libbpf-dev
      - libcurl-openssl4
      - libelf
      - libsystemd
      - libtbb-dev
      - libtool
      - libzstd1
      - linux-headers
      - llvm-${{vars.llvm-vers}}
      - m4
      - make
      - nlohmann-json
      - openssl-dev
      - patch
      - perl
      - protobuf-dev
      - re2-dev
      - systemd-dev
      # TODO: Believe these are needed for 'make sinsp' to succeed.
      - tinydir
      - uthash
      - valijson
      - yaml-cpp-dev
      - yaml-dev
      - zlib-dev
      - zstd
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/falcosecurity/falco
      tag: ${{package.version}}
      expected-commit: 2804d60bd2f9088bf17b868d7feb19e9fb4372ee
      recurse-submodules: true

  - uses: patch
    with:
      # to prevent usage of vendored tbb
      patches: tbb.patch libcurl-include.patch

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/falco
      install -Dm755 ./falco.yaml "${{targets.destdir}}"/etc/falco/falco.yaml

  - runs: |
      sed -i '165s/${FALCO_LIBRARIES}/${FALCO_LIBRARIES} zstd/' userspace/falco/CMakeLists.txt

  - working-directory: /home/build/build
    # NOTE: These flags have been specifically set. Do not go changing these
    # as part of development! They need to be set as they are.
    # TODO: REMOVE THIS COMMENT ABOVE BEFORE MERGING
    pipeline:
      - runs: |
          cmake                                     \
            -Wno-dev                                \
            -DCMAKE_INSTALL_PREFIX=/usr             \
            -DCMAKE_INSTALL_LIBDIR=lib              \
            -DCMAKE_BUILD_TYPE=MinSizeRel           \
            -DUSE_BUNDLED_TBB=OFF                   \
            -DUSE_BUNDLED_RE2=OFF                   \
            -DUSE_BUNDLED_JSONCPP=OFF               \
            -DBUILD_FALCO_MODERN_BPF=ON             \
            -DBUILD_STATIC_LIBS=OFF                 \
            -DUSE_BUNDLED_DEPS=OFF                  \
            -DBUILD_SHARED_LIBS=ON                  \
            -DBUILD_DRIVER=OFF                      \
            -DFALCOSECURITY_SHARED_LIBS_VERSION=0   \
            -DFALCOSECURITY_SHARED_LIBS_SOVERSION=0 \
            ..
      - name: Patch falcosecurity-libs
        runs: |
          # add appropriate include paths to fix gvisor on x86_64
          # lots of good discussion and help from an upstream maintainer (@LucaGuerra) https://github.com/wolfi-dev/os/pull/26622#discussion_r1768659440
          sed -i '/set_property(TARGET scap_engine_gvisor_o PROPERTY POSITION_INDEPENDENT_CODE ON)/a \
          target_include_directories( \
              scap_engine_gvisor_o \
              PRIVATE \
                  $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}> \
                  $<BUILD_INTERFACE:${LIBS_DIR}> \
                  $<BUILD_INTERFACE:${LIBS_DIR}/userspace> \
                  $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}> \
          )' falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libscap/engine/gvisor/CMakeLists.txt
      - runs: |
          make falco -j$(nproc)
          make install PREFIX="/usr" DESTDIR="${{targets.destdir}}"
          install -Dm755 ./userspace/falco/falco "${{targets.destdir}}"/usr/bin/falco
      # TODO: This should be removed after falcosecurity/libs is fixed to build pman staticly.
      # We use an exit 0 to allow the install failure to be suppressed so that nothing breaks once
      # falcosecurity/libs is fixed.
      - runs: |
          install -D -m755 ./libpman/libpman.so "${{targets.destdir}}"/usr/lib || exit 0

  # Do not conflict with the falco-rules and falcoctl package.
  - runs: |
      rm -f "${{targets.destdir}}"/etc/falco/falco_rules.yaml
      rm -f "${{targets.destdir}}"/usr/bin/falcoctl

  - uses: strip

subpackages:
  - name: falco-src
    description: Falco kernel module sources
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr
          mv "${{targets.destdir}}"/usr/src "${{targets.contextdir}}"/usr/src

  - name: falco-dev
    description: Falco development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: falcosecurity/falco

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        falco --version
        falco --help
