package:
  name: fulcio
  version: 1.6.5
  epoch: 0
  description: Sigstore OIDC PKI
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7920be28f7f58020c4da8ab9bb78554ad7cd67ea
      repository: https://github.com/sigstore/fulcio
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w
      modroot: .
      output: fulcio
      packages: ./

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/fulcio
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: Check Fulcio version
      runs: |
        # Check the Fulcio version
        fulcio version
        fulcio --help
    - name: Run fulcio server
      runs: |
        fulcio serve --ca=ephemeralca &
        echo "Sleep 2 seconds and try to retrieve root certificate"
        sleep 2
        curl localhost:8080/api/v1/rootCert
