package:
  name: gcc
  version: 13.3.0
  epoch: 3
  description: "the GNU compiler collection"
  copyright:
    - license: GPL-3.0-or-later WITH GCC-exception-3.1
  resources:
    cpu: 16
    memory: 16Gi
  dependencies:
    runtime:
      - binutils
      - libstdc++-dev
      - posix-cc-wrappers

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex-dev
      - gawk
      - gmp-dev
      - isl-dev
      - make
      - mpc-dev
      - mpfr-dev
      - patch
      - texinfo
      - wolfi-baselayout
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/gcc/gcc-${{package.version}}/gcc-${{package.version}}.tar.xz
      expected-sha512: ed5f2f4c6ed2c796fcf2c93707159e9dbd3ddb1ba063d549804dd68cdabbb6d550985ae1c8465ae9a336cfe29274a6eb0f42e21924360574ebd8e5d5c7c9a801

  - name: 'Set up build directory'
    runs: |
      mkdir build

  - name: 'Configure GCC'
    runs: |
      # Check https://aws.amazon.com/ec2/instance-types/ and
      # https://cloud.google.com/compute/docs/general-purpose-machines
      # for most current CPU types on arm64 and x86 to set mtune to
      # the current generation of CPUs. Other clouds are typically
      # roughly at the same level (Azure, Oracle, IBM, Linode, etc).
      case "${{build.arch}}" in
        "aarch64")
          march=armv8-a+crc+crypto
          mtune=neoverse-v2
          ;;
        "x86_64")
          march=x86-64-v2
          mtune=sapphirerapids
          ;;
      esac
      cd build
      ../configure \
        --prefix=/usr \
        --disable-nls \
        --disable-werror \
        --with-pkgversion='Wolfi ${{package.full-version}}' \
        --with-glibc-version=2.35 \
        --enable-initfini-array \
        --disable-nls \
        --disable-multilib \
        --enable-host-shared \
        --enable-shared \
        --enable-threads \
        --enable-tls \
        --enable-default-pie \
        --enable-default-ssp \
        --with-system-zlib \
        --with-arch=$march \
        --with-tune=$mtune \
        --enable-languages=c,c++,fortran,jit,go \
        --enable-bootstrap \
        --enable-gnu-indirect-function \
        --enable-gnu-unique-object \
        --enable-cet=auto \
        --enable-link-mutex \
        --with-gcc-major-version-only \
        --with-linker-hash-style=gnu

  - runs: |
      make -C build -j$(nproc)

  - runs: |
      make -C build -j$(nproc) install DESTDIR="${{targets.destdir}}"

  # We don't want to keep the .la files.
  - runs: |
      find ${{targets.destdir}} -name '*.la' -print -exec rm \{} \;

  - runs: |
      chmod 755 ${{targets.destdir}}/usr/lib64/libgcc_s.*

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - uses: strip

subpackages:
  - name: 'gcc-doc'
    pipeline:
      - uses: split/manpages

  - name: 'libstdc++'
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/*++.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: 'libstdc++-dev'
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mkdir -p "${{targets.subpkgdir}}"/usr/include
          mkdir -p "${{targets.subpkgdir}}"/usr/share/gcc-${{vars.major-version}}/python/libstdcxx
          mv "${{targets.destdir}}"/usr/lib64/*++.a "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/lib64/libstdc++.so "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/include/*++* "${{targets.subpkgdir}}"/usr/include/
          mv "${{targets.destdir}}"/usr/share/gcc-${{vars.major-version}}/python/libstdcxx/* \
            "${{targets.subpkgdir}}"/usr/share/gcc-${{vars.major-version}}/python/libstdcxx/

  - name: "libquadmath"
    description: "128-bit math library provided by GCC"
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libquadmath.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "libgfortran"
    description: "Fortran runtime library provided by GCC"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libgfortran.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "gfortran"
    description: "GNU Fortran Compiler"
    pipeline:
      - runs: |
          _libexecdir=/usr/libexec/gcc/${{host.triplet.gnu}}/${{vars.major-version}}
          _libdir=/usr/lib/gcc/${{host.triplet.gnu}}/${{vars.major-version}}

          for i in "$_libexecdir" "$_libdir" usr/lib64 usr/bin; do
            mkdir -p "${{targets.subpkgdir}}"/$i
          done

          mv "${{targets.destdir}}"/usr/bin/*fortran "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/lib64/libgfortran* "${{targets.subpkgdir}}"/usr/lib64
          [ -f "${{targets.destdir}}"/usr/lib64/libquadmath* ] && mv "${{targets.destdir}}"/usr/lib64/libquadmath* "${{targets.subpkgdir}}"/usr/lib64

          mv "${{targets.destdir}}"/$_libdir/finclude "${{targets.subpkgdir}}"/$_libdir
          mv "${{targets.destdir}}"/$_libexecdir/f951 "${{targets.subpkgdir}}"/$_libexecdir
    dependencies:
      runtime:
        - gcc
        - libgfortran

  - name: "libgccjit"
    description: "GCC JIT library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libgccjit.so.* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libgccjit-dev"
    description: "GCC JIT library headers"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mkdir -p "${{targets.subpkgdir}}"/usr/include

          mv "${{targets.destdir}}"/usr/lib/libgccjit.so "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/include/libgccjit*.h "${{targets.subpkgdir}}"/usr/include/

  - name: "libssp"
    description: "GCC stack protection library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libssp* "${{targets.subpkgdir}}"/usr/lib64

  - name: "libgomp"
    description: "GNU parallel programming library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libgomp.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "libgcc"
    description: "GCC runtime library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libgcc_s.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "libatomic"
    description: "GCC atomic library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libatomic.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "libgo"
    description: "GCC go runtime library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/libgo.so.* "${{targets.subpkgdir}}"/usr/lib64/

  - name: "gcc-go"
    description: "GCC go compiler"
    dependencies:
      provides:
        - go-bootstrap=1.18
    pipeline:
      - runs: |
          _libexecdir=/usr/libexec/gcc/${{host.triplet.gnu}}/${{vars.major-version}}

          for i in "$_libexecdir" usr/lib64 usr/bin; do
            mkdir -p "${{targets.subpkgdir}}"/$i
          done

          mv "${{targets.destdir}}"/usr/bin/${{host.triplet.gnu}}-gccgo "${{targets.subpkgdir}}"/usr/bin/
          for i in go gofmt gccgo; do
            mv "${{targets.destdir}}"/usr/bin/$i "${{targets.subpkgdir}}"/usr/bin/
          done

          mv "${{targets.destdir}}"/usr/lib64/go "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/lib64/libgo.a "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/lib64/libgobegin.a "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/lib64/libgolibbegin.a "${{targets.subpkgdir}}"/usr/lib64/
          mv "${{targets.destdir}}"/usr/lib64/libgo.so "${{targets.subpkgdir}}"/usr/lib64/

          for i in cgo go1; do
            mv "${{targets.destdir}}"/"$_libexecdir"/$i "${{targets.subpkgdir}}"/"$_libexecdir"/
          done

test:
  environment:
    contents:
      packages:
        - glibc-dev
  pipeline:
    - name: Check basic usage of top level & libexec binaries
      runs: |
        # Check C frontend compiler
        gcc --version | grep ${{package.version}}
        # Check C++ frontend compiler
        g++ --version | grep ${{package.version}}
        # Check C empty translation unit compilation
        : > empty.c
        gcc -c empty.c

        # Check C++ empty translation unit compilation
        rm -f empty.cpp
        : > empty.cpp
        g++ -c empty.cpp
    - name: hello world c
      runs: |
        cat >hello.c <<"EOF"
        #include <stdio.h>
        int main(int argc, char* argv[]) {
            printf("hello-c");
            return 0;
        }
        EOF

        gcc -o hello-c hello.c
        out=$(./hello-c)
        [ "$out" = "hello-c" ]
    - name: hello world c++
      runs: |
        cat >hello.cpp <<"EOF"
        #include <iostream>
        int main() {
            std::cout << "hello-c++";
            return 0;
        }
        EOF

        g++ -o hello-c++ hello.cpp
        out=$(./hello-c++)
        [ "$out" = "hello-c++" ]

update:
  enabled: true
  release-monitor:
    identifier: 6502
