package:
  name: jenkins-docker
  version: "2.480"
  epoch: 0
  description: Docker compatbility scripts and tooling for Jenkins
  copyright:
    - license: MIT
  dependencies:
    # https://github.com/jenkinsci/docker/blob/5575a3c8fe959449570de9eb03e6cb3127d8f389/alpine/hotspot/Dockerfile#L42
    runtime:
      - bash
      - coreutils
      - curl
      - git
      - git-lfs
      - gnupg
      - openssh-client
      - tini
      - ttf-dejavu
      - tzdata
      - unzip
      - jenkins-plugin-manager-compat

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/docker
      tag: ${{package.version}}
      expected-commit: 97b425c4f4afaac5ee256ec1127ee1c14924001b

  # https://github.com/jenkinsci/docker/blob/master/alpine/hotspot/Dockerfile#L136
  - runs: |
      install -Dm755 jenkins-support ${{targets.destdir}}/usr/local/bin/jenkins-support
      install -Dm755 jenkins.sh ${{targets.destdir}}/usr/local/bin/jenkins.sh
      install -Dm755 jenkins-plugin-cli.sh ${{targets.destdir}}/bin/jenkins-plugin-cli

update:
  enabled: true
  github:
    identifier: jenkinsci/docker

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        jenkins-support --version
        jenkins-support --help
