package:
  name: libpng
  version: 1.6.44
  epoch: 1
  description: Portable Network Graphics library
  copyright:
    - license: Libpng

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gawk
      - libtool
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pnggroup/libpng
      tag: v${{package.version}}
      expected-commit: f5e92d76973a7a53f517579bc95d61483bf108c0

  - runs: autoreconf -vif

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libpng-doc
    pipeline:
      - uses: split/manpages
    description: libpng manpages

  - name: libpng-static
    description: libpng static library
    pipeline:
      - uses: split/static

  - name: libpng-dev
    pipeline:
      - uses: split/dev
    dependencies:
      provides:
        # Upstream has interesting setup for versioned and unversioned
        # install locations, which are very libpng specific. Support
        # such install layout with melange SCA by augumenting the
        # necessory provides, which is installed as a symlink.
        - pc:libpng.pc
      runtime:
        - libpng
    description: libpng dev
    test:
      pipeline:
        - runs: |
            libpng-config --version
            libpng-config --help
            libpng16-config --version
            libpng16-config --help

  - name: libpng-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: libpng utils
    test:
      pipeline:
        - runs: |
            png-fix-itxt --version
            png-fix-itxt --help

update:
  enabled: true
  github:
    identifier: pnggroup/libpng
    strip-prefix: v
    use-tag: true
