package:
  name: libsdl3
  version: 3.1.3
  epoch: 0
  description: Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D.
  copyright:
    - license: Zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libsdl-org/SDL
      tag: preview-${{package.version}}
      expected-commit: e292d1f5ace469f718d7b6b4dec8c28e37dcaa0e

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      rm ${{targets.destdir}}/usr/share/licenses/SDL3/LICENSE.txt
      rm -r ${{targets.destdir}}/usr/share

subpackages:
  - name: ${{package.name}}-dev
    dependencies:
      runtime:
        - libsdl3
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: libsdl-org/SDL
    strip-prefix: preview-
    tag-filter-prefix: preview
    use-tag: true

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev
        - pkgconf
  pipeline:
    - runs: |
        set -euo pipefail
        pkg-config --modversion sdl3 | grep -q "${{package.version}}"
