package:
  name: logstash-exporter
  version: 1.8.0
  epoch: 0
  description: Prometheus exporter for Logstash written in Go
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    GITHUB_REPO: "github.com/kuskoman/logstash-exporter"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1e60b12299b747a658185ef01cc7364f43b23995
      repository: https://github.com/kuskoman/logstash-exporter
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/exporter/main.go
      ldflags: -s -w -X ${GITHUB_REPO}/config.Version="${{package.version}}" -X ${GITHUB_REPO}/config.GitCommit="$(git rev-parse --short HEAD)" -X ${GITHUB_REPO}/config.BuildDate="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      output: logstash-exporter

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - "-pre*"
  github:
    identifier: kuskoman/logstash-exporter
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        logstash-exporter -version
        logstash-exporter --version
        logstash-exporter --help
