package:
  name: modelmesh-runtime-adapter
  version: 0.12.0
  epoch: 0
  description: Unified runtime-adapter package of the sidecar containers which run in the modelmesh pods
  dependencies:
    runtime:
      - py3-asn1-modules
      - py3-cachetools
      - py3-google-auth
      - py3-google-auth-oauthlib
      - py3-importlib-metadata
      - py3-numpy
      - py3-oauthlib
      - py3-requests-oauthlib
      - py3-rsa
      - py3-tensorflow-core
      - py3-zipp

data:
  - name: binaries
    items:
      mlserver-adapter: model-mesh-mlserver-adapter
      ovms-adapter: model-mesh-ovms-adapter
      torchserve-adapter: model-mesh-torchserve-adapter
      triton-adapter: model-mesh-triton-adapter
      puller: model-serving-puller

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kserve/modelmesh-runtime-adapter
      expected-commit: 5d0c9a008cce30b2b3839874c9f1f2ca8ddc38de
      tag: v${{package.version}}

subpackages:
  - range: binaries
    name: "modelmesh-runtime-adapter-${{range.key}}"
    description: "${{range.key}} binary for modelmesh-runtime-adapter"
    pipeline:
      - uses: go/build
        with:
          output: ${{range.key}}
          packages: ./${{range.value}}
          ldflags: -s

  - name: "modelmesh-runtime-adapter-compat"
    description: "compat package to place binaries in location expected by upstream helm chart"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/opt/app"
          ln -sf /usr/bin/mlserver-adapter ${{targets.subpkgdir}}/opt/app/mlserver-adapter
          ln -sf /usr/bin/ovms-adapter ${{targets.subpkgdir}}/opt/app/ovms-adapter
          ln -sf /usr/bin/torchserve-adapter ${{targets.subpkgdir}}/opt/app/torchserve-adapter
          ln -sf /usr/bin/triton-adapter ${{targets.subpkgdir}}/opt/app/triton-adapter
          ln -sf /usr/bin/puller ${{targets.subpkgdir}}/opt/app/puller

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-mlserver-adapter
        - ${{package.name}}-ovms-adapter
        - ${{package.name}}-torchserve-adapter
        - ${{package.name}}-triton-adapter
        - ${{package.name}}-puller
        - ${{package.name}}-compat
  pipeline:
    - name: TEST
      runs: |
        export CONTAINER_MEM_REQ_BYTES=1
        torchserve-adapter 2>&1 | grep -q 'TorchServe runtime adapter started'
        ovms-adapter 2>&1 | grep -q 'OVMS Runtime started'
        triton-adapter 2>&1 | grep -q 'Triton runtime adapter started'
        mlserver-adapter 2>&1 | grep -q 'MLServer runtime adapter started'
        puller 2>&1 | grep -q 'starting clean up of cached clients'

update:
  enabled: true
  github:
    identifier: kserve/modelmesh-runtime-adapter
    strip-prefix: v
