package:
  name: mysql-9.0
  version: 9.0.1
  epoch: 0
  description: "The MySQL open source relational database"
  copyright:
    - license: GPL-2.0-only # https://downloads.mysql.com/docs/licenses/mysqld-9.0-gpl-en.pdf
  resources:
    cpu: 30
    memory: 60Gi
  dependencies:
    runtime:
      - ${{package.name}}-client
      - pwgen
    provides:
      - mysql=${{package.full-version}}

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - graphviz
      - libaio-dev
      - libevent-dev
      - libtirpc-dev
      - linux-pam-dev
      - ncurses-dev
      - openssl-dev
      - pcre2-dev
      - readline-dev
      - rpcsvc-proto
      - wolfi-baselayout
      - xz-dev
      - zlib-dev

pipeline:
  - working-directory: /home/build/mysql
    pipeline:
      - uses: fetch
        with:
          uri: https://dev.mysql.com/get/Downloads/${{package.name}}/mysql-${{package.version}}.tar.gz
          expected-sha256: 18fa65f1ea6aea71e418fe0548552d9a28de68e2b8bc3ba9536599eb459a6606
      - uses: cmake/configure
        with:
          opts: |
            -DWITH_UNIT_TESTS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DSYSCONFDIR=/etc \
            -DMYSQL_DATADIR=/var/lib/mysql \
            -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
            -DDEFAULT_CHARSET=utf8mb4 \
            -DDEFAULT_COLLATION=utf8mb4_general_ci \
            -DENABLED_LOCAL_INFILE=ON \
            -DINSTALL_INFODIR=share/info \
            -DINSTALL_MANDIR=share/man \
            -DINSTALL_PLUGINDIR=lib/${{package.name}}/plugin \
            -DINSTALL_INCLUDEDIR=include/mysql \
            -DINSTALL_DOCREADMEDIR=share/doc/${{package.name}} \
            -DINSTALL_SUPPORTFILESDIR=share/support/${{package.name}} \
            -DINSTALL_MYSQLSHAREDIR=share/${{package.name}} \
            -DINSTALL_DOCDIR=share/doc/${{package.name}} \
            -DWITH_ASAN=OFF \
            -DWITH_JEMALLOC=OFF \
            -DWITH_LIBWRAP=OFF \
            -DWITH_SYSTEMD=OFF \
            -DWITH_SSL=system \
            -DWITH_VALGRIND=OFF \
            -DWITH_ZLIB=system
      - uses: cmake/build
      - uses: cmake/install
      - name: "Remove extras"
        runs: |
          rm -r "${{targets.destdir}}"/usr/mysql-test/

  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    description: "headers for mysql"
    dependencies:
      provides:
        - mysql-dev=${{package.full-version}}
    pipeline:
      - uses: split/dev

  - name: "${{package.name}}-client"
    dependencies:
      provides:
        - mysql-client=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/mysql "${{targets.subpkgdir}}"/usr/bin/

  - name: "${{package.name}}-oci-entrypoint"
    description: Entrypoint for MySQL in OCI containers
    dependencies:
      runtime:
        - bash
        - busybox
        - openssl
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod +x ${{targets.subpkgdir}}/usr/bin/docker-entrypoint.sh

  - name: "${{package.name}}-oci-entrypoint-compat"
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -sf /usr/bin/docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh
    dependencies:
      runtime:
        - "${{package.name}}-oci-entrypoint"

update:
  enabled: true
  github:
    identifier: mysql/mysql-server
    strip-prefix: mysql-
    use-tag: true
    tag-filter: mysql-9.0.

test:
  environment:
    contents:
      packages:
        - ${{package.name}}
        - ${{package.name}}-client
    environment:
      DBDATA: /var/lib/mysql
  pipeline:
    - name: Check versions
      runs: |
        mysql --version |grep "${{package.version}}"
        mysqladmin --version | grep "${{package.version}}"
    - name: Test
      uses: test/daemon-check-output
      with:
        setup: |
          mkdir -p "$DBDATA" /var/tmp /var/log/mysql /run/mysqld
          mysqld --initialize-insecure --datadir="$DBDATA"
        start: mysqld --user=root --datadir="$DBDATA"
        post: |
          mysqladmin --user=root ping --wait=5
        timeout: 60
        expected_output: |
          starting as process
          ready for connections
