package:
  name: neovim
  version: 0.10.2
  epoch: 0
  description: "Vim-fork focused on extensibility and agility"
  copyright:
    - license: Apache-2.0 AND Vim
  dependencies:
    provides:
      # workaround missing provides in lua-lpeg and failure to rebuild lua-lpeg
      - so:/usr/lib/lua/5.1/lpeg.so
    runtime:
      - lua5.1-lpeg

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - gettext-dev
      - gperf
      - libtermkey
      - libtermkey-dev
      - libuv-dev
      - libvterm-dev
      - lua-luv
      - lua-luv-dev
      - lua5.1-lpeg
      - lua5.1-mpack
      - luajit-dev
      - msgpack-c-dev
      - openssf-compiler-options
      - samurai
      - tree-sitter-dev
      - unibilium-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neovim/neovim
      tag: v${{package.version}}
      expected-commit: 8b98642002d0506d20628683958cb5c97a0dad80

  # TODO: Don't rely on bundled treesitter grammars
  - runs: |
      cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo \
        -DUSE_BUNDLED=OFF \
        -DUSE_BUNDLED_TS_PARSERS=ON
      cmake --build .deps

  - runs: |
      cmake -B output -G Ninja \
       -DCMAKE_BUILD_TYPE=RelWithDebInfo \
       -DCMAKE_INSTALL_PREFIX=/usr \
       -DCMAKE_INSTALL_LIBDIR=lib \
       -DENABLE_JEMALLOC=FALSE \
       -DENABLE_LTO=TRUE \
       -DCMAKE_VERBOSE_MAKEFILE=TRUE \
       -DCI_BUILD=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

test:
  pipeline:
    - name: Verify vim installation
      runs: |
        nvim -V1 --version || exit 1
        nvim --version
        nvim --help

update:
  enabled: true
  github:
    identifier: neovim/neovim
    strip-prefix: v
    tag-filter: v
