package:
  name: oauth2-proxy
  version: 7.7.1
  epoch: 0
  description: Reverse proxy and static file server that provides authentication using various providers to validate accounts by email, domain or group.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - openssl
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/oauth2-proxy/oauth2-proxy/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 05a849bb79a6cd160779982f5564c0551e20a08e4c4ff947882817cc638a516f

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3

  - uses: go/build
    with:
      packages: .
      output: oauth2-proxy
      ldflags: -s -w -X github.com/oauth2-proxy/oauth2-proxy/v7/pkg/version.Version=${{package.version}}

  - runs: |
      # Make sure there is at least an empty key file.
      # This is useful for GCP App Engine custom runtime builds, because you cannot use multiline variables in their app.yaml, so you have to build the
      # key into the container and then tell it where it is by setting OAUTH2_PROXY_JWT_KEY_FILE=/etc/ssl/private/jwt_signing_key.pem in app.yaml instead.
      mkdir -p "${{targets.destdir}}/etc/ssl/private/"
      touch "${{targets.destdir}}/etc/ssl/private/jwt_signing_key.pem"

  - uses: strip

update:
  enabled: true
  github:
    identifier: oauth2-proxy/oauth2-proxy
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        oauth2-proxy --version
