package:
  name: openbao
  version: 2.0.2
  epoch: 1
  description: OpenBao exists to provide a software solution to manage, store, and distribute sensitive data including secrets, certificates, and keys.
  copyright:
    - license: MPL-2.0

# NOTE: openbao UI is not enabled for now ; see https://github.com/openbao/openbao/issues/129
# several sections need to be uncommented to embed UI in the tool

# NOTE: uncomment when enabling embedding of UI
# environment:
#   contents:
#     packages:
#       - busybox
#       - ca-certificates-bundle
#       - nodejs
#       - npm
#       - yarn
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openbao/openbao
      tag: v${{package.version}}
      expected-commit: 96853bb4de27ab8ffd1b0c2898c691460d43edeb
  - runs: |
      # NOTE: uncomment when enabling embedding of UI
      # make ember-dist
  - uses: go/build
    with:
      # NOTE: add "ui" tag when enabling embedding of UI
      tags: "openbao"
      packages: .
      output: bao
      ldflags: |
        -X github.com/openbao/openbao/version.fullVersion=${{package.version}}
        -X github.com/openbao/openbao/version.GitCommit='$(git rev-parse HEAD)'
        -X github.com/openbao/openbao/version.BuildDate='$(date -u +"%Y-%m-%dT%H:%M:%SZ")'

subpackages:
  - name: openbao-compat
    description: "Compatibility package to allow replacing vault image"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin
          ln -sf /usr/bin/bao ${{targets.contextdir}}/bin/bao
          ln -sf /bin/bao ${{targets.contextdir}}/bin/vault

update:
  enabled: true
  github:
    identifier: openbao/openbao
    strip-prefix: v

test:
  pipeline:
    - runs: |
        bao --version
