package:
  name: percona-xtrabackup-8.4
  version: 8.4.0.1
  epoch: 0
  description: Open source hot backup tool for InnoDB and XtraDB databases
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - percona-xtrabackup=${{package.full-version}}
    runtime:
      - perl

# Replace the last `.` with `-` to fetch the correct tag.
var-transforms:
  - from: ${{package.version}}
    match: '\.(\d+)$'
    replace: "-$1"
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - bpftool
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates
      - clang-18
      - clang-18-dev
      - clang-18-extras
      - cmake
      - curl
      - curl-dev
      - elfutils-dev
      - eudev-dev
      - gcc-12-default
      - git
      - grpc-dev
      - hardening-check
      - isl-dev
      - libaio-dev
      - libbpf
      - libbpf-dev
      - libcurl-openssl4
      - libelf-static
      - libev-dev
      - libgcrypt-dev
      - liblz4-1
      - librtmp
      - libtool
      - lsb-release-minimal
      - lz4
      - lz4-dev
      - mpc-dev
      - ncurses-dev
      - numactl-dev
      - openldap-dev
      - openssl-dev
      - pkgconf
      - procps-dev
      - protobuf-dev
      - py3-docutils
      - py3-sphinx
      - qpress
      - rsync
      - rtmpdump-dev
      - socat
      - vim
      - yaml-cpp-dev
      - zlib-dev
      - zstd

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/percona-xtrabackup
      tag: percona-xtrabackup-${{vars.mangled-package-version}}
      expected-commit: da6e1abde099d91b9b725f44b944f95db156cf7f
      recurse-submodules: true

  - runs: |
      mkdir build && cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DWITH_BOOST=PATH-TO-BOOST-LIBRARY \
        -DDOWNLOAD_BOOST=ON \
        -DBUILD_CONFIG=xtrabackup_release \
        -DWITH_MAN_PAGES=OFF \
        ..
      make -j$(nproc)

  - working-directory: build
    uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/xtrabackup/bin/
          for bin in $(find "${{targets.destdir}}"/usr/bin -type f -executable); do
            ln -sf /usr/bin/$(basename $bin) ${{targets.contextdir}}/usr/local/xtrabackup/bin/$(basename $bin)
          done

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/man/man1
          mv "${{targets.destdir}}"/usr/man/man1/* "${{targets.contextdir}}"/usr/share/man/man1/
          rm -rf "${{targets.destdir}}"/usr/man
    description: ${{package.name}} manpages

  - name: "${{package.name}}-test"
    description: "Provides xtrabackup-test"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr
          mv "${{targets.destdir}}"/usr/xtrabackup-test ${{targets.contextdir}}/usr/xtrabackup-test
          rm -rf "${{targets.destdir}}"/usr/xtrabackup-test

update:
  enabled: true
  github:
    identifier: percona/percona-xtrabackup
    strip-prefix: percona-xtrabackup-
    use-tag: true
    tag-filter: percona-xtrabackup-8.4
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - name: Check binaries
      runs: |
        for bin in /usr/local/xtrabackup/bin/*; do
          $bin --version
        done
    - name: Test xbcrypt
      runs: |
        echo "This is a test" | xbcrypt -a aes256 -k testkey123456789 > /tmp/encrypted.xb
        xbcrypt -d -a aes256 -k testkey123456789 -i /tmp/encrypted.xb
    - name: Test xbstream
      runs: |
        echo "Test data" > file1.txt
        echo "More test data" > file2.txt
        xbstream -c file1.txt file2.txt > stream_output.xbstream
        mkdir extract_dir
        cat stream_output.xbstream | xbstream -x -C extract_dir
        test -f extract_dir/file1.txt
        test -f extract_dir/file2.txt
