package:
  name: php-8.2-pecl-sqlsrv
  version: 5.12.0
  epoch: 0
  description: "Provides PHP 8.2 Microsoft Drivers for SQL Server (SQLSRV) - PECL"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc
      - libtool
      - openssf-compiler-options
      - php-8.2-dev
      - unixodbc-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/sqlsrv-${{package.version}}.tgz
      expected-sha256: a9ebb880b2a558d3d6684f6e6802c53c5bffa49e1ee60d1473a7124fc9cb72ad

  - uses: pecl/phpize

  - uses: autoconf/make

  # TODO: This is a temporary workaround until the pecl/install pipelines
  # propagates through.
  # https://github.com/chainguard-dev/melange/pull/1068
  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=sqlsrv.so" > ${{targets.destdir}}/etc/php/conf.d/sqlsrv.ini

  - uses: strip

update:
  enabled: false
  exclude-reason: >
    TODO(vaikas): I can find the releases in github but building it does not work with fetching from there like it does when you use fetch. Also seems like I can't watch the github repo for new releases, yet use the fetch above together?

