package:
  name: protobuf
  version: 3.27.4
  epoch: 1
  description: Library for extensible, efficient structure packing
  copyright:
    - license: BSD-3-Clause

var-transforms:
  # 3.26.1 -> 26.1
  # TODO: Figure out how to make this 26.1.0
  - from: ${{package.version}}
    match: \d+\.(\d+\.\d+)
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - git
      - libtool
      - samurai
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/protocolbuffers/protobuf
      tag: v${{package.version}}
      expected-commit: 80d48ae92d3007caac5eab0a8f8ee4e57f3a921e

  - runs: |
      cd third_party
      git submodule update --init --recursive

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=Release \
        -Dprotobuf_ABSL_PROVIDER=package \
        -Dprotobuf_BUILD_TESTS=OFF \
        -Dprotobuf_BUILD_LIBUPB=OFF
      ninja -C build
      DESTDIR=${{targets.destdir}} ninja -C build install

  - uses: strip

subpackages:
  - name: protobuf-dev
    description: protobuf dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - protobuf
        - zlib-dev
        - protoc
        - libprotoc
        - libprotobuf
        - libprotobuf-lite

  - name: protoc
    description: Protocol buffer compiler binary and library
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv ${{targets.destdir}}/usr/bin/protoc-${{vars.mangled-package-version}}.0 ${{targets.subpkgdir}}/usr/bin/
          mv ${{targets.destdir}}/usr/bin/protoc ${{targets.subpkgdir}}/usr/bin/protoc
    test:
      pipeline:
        - name: Verify protoc installation
          runs: |
            protoc --version || exit 1
            protoc-27.4.0 --version
            protoc-27.4.0 --help
        - name: Compile sample proto file
          runs: |
            echo 'syntax = "proto3"; message Test { string name = 1; }' > test.proto
            protoc --proto_path=. --python_out=. test.proto || exit 1

  - name: libprotoc
    description: Runtime library for Protocol Buffer compiler
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/libprotoc*.so.* ${{targets.subpkgdir}}/usr/lib/

  - name: libprotobuf
    description: Runtime library for C++ users of protocol buffers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/libprotobuf.so.* ${{targets.subpkgdir}}/usr/lib/

  - name: libprotobuf-lite
    description: Runtime library for C++ users with 'lite runtime' setting of protocol buffers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/libprotobuf-lite.so.* ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  github:
    identifier: protocolbuffers/protobuf
    strip-prefix: v
    use-tag: true
    tag-filter: "v3."

test:
  environment:
    contents:
      packages:
        - protobuf-dev
        - protobuf
        - libprotoc
        - libprotobuf
        - libprotobuf-lite
  pipeline:
    - runs: |
        protoc --help
