package:
  name: py3-docutils
  version: 0.21.2
  epoch: 1
  description: Documentation Utilities for Python3
  copyright:
    - license: BSD-2-Clause AND GPL-3.0-or-later AND Python-2.0
  dependencies:
    runtime:
      - py3-pip
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${{package.version}}.tar.gz
      expected-sha256: 3a6b18732edf182daa3cd12775bbb338cf5691468f91eeeb109deff6ebfa986f

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3849

test:
  pipeline:
    - runs: |
        LIBRARY="docutils"
        IMPORT_STATEMENT="from docutils import nodes"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
        docutils --version
        docutils --help
        rst2html --version
        rst2html --help
        rst2html4 --version
        rst2html4 --help
        rst2html5 --version
        rst2html5 --help
        rst2latex --version
        rst2latex --help
        rst2man --version
        rst2man --help
        rst2odt --version
        rst2odt --help
        rst2pseudoxml --version
        rst2pseudoxml --help
        rst2s5 --version
        rst2s5 --help
        rst2xetex --version
        rst2xetex --help
        rst2xml --version
        rst2xml --help
