package:
  name: py3-tenacity
  version: 9.0.0
  epoch: 1
  description: General-purpose retrying library, written in Python, to simplify the task of adding retry behavior to just about anything
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tenacity
  import: tenacity

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jd/tenacity.git
      tag: ${{package.version}}
      expected-commit: a662bbb487cd6d34541824589f8e8c7a1f7791bb

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
    - uses: python/import
      with:
        imports: |
          import tenacity

update:
  enabled: true
  github:
    identifier: jd/tenacity
    use-tag: true
  ignore-regex-patterns:
    - mergify2-
