package:
  name: py3-blinker
  version: 1.8.2
  epoch: 1
  description: Fast, simple object-to-object and broadcast signaling
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: blinker
  import: blinker

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-flit-core
      - py3-supported-gpep517

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pallets-eco/blinker/
      tag: ${{package.version}}
      expected-commit: 0a6be69aaaf72917bbedf41643f83128c8623075

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  github:
    identifier: pallets-eco/blinker
