package:
  name: py3-sphinx-rtd-theme
  version: 3.0.1
  epoch: 0
  description: Read the Docs theme for Sphinx
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-docutils
      - py3-sphinx-7
      - py3-sphinxcontrib-jquery

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7b894f5e7a5053dd35de406bc779020c229f20a9
      repository: https://github.com/readthedocs/sphinx_rtd_theme
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: readthedocs/sphinx_rtd_theme
    use-tag: true

test:
  environment:
    contents:
      packages:
        - python-3
        - py3-sphinx-7
        - py3-docutils
        - py3-sphinxcontrib-jquery
  pipeline:
    - name: Verify installation of Sphinx RTD theme
      runs: |
        python3 -c "import sphinx_rtd_theme" || exit 1
    - name: Generate documentation using the theme
      runs: |
        mkdir -p test_docs
        cd test_docs
        sphinx-quickstart -q -p "Test Project" -a "Author" -v "0.1" --ext-autodoc --ext-viewcode || exit 1

        # Modify conf.py to use the sphinx_rtd_theme
        sed -i "s/html_theme = .*/html_theme = 'sphinx_rtd_theme'/g" conf.py

        # Build the documentation
        sphinx-build -b html . _build/html || exit 1
    - name: Check if HTML output was generated
      runs: |
        test -f test_docs/_build/html/index.html || exit 1
