package:
  name: py3-argon2-cffi-bindings
  version: 21.2.0
  epoch: 3
  description: Low-level CFFI bindings for Argon2
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: argon2-cffi-bindings
  import: no-valid-import

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - argon2
      - argon2-dev
      - py3-supported-build-base-dev
  environment:
    ARGON2_CFFI_USE_SYSTEM: 1

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2bf609f920d83a081a5787425b9eb1c95ecf6e0c
      repository: https://github.com/hynek/argon2-cffi-bindings
      tag: ${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-cffi
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: hynek/argon2-cffi-bindings
    use-tag: true
