package:
  name: py3-face
  version: 22.0.0
  epoch: 3
  description: A command-line application framework (and CLI parser). Friendly for users, full-featured for developers.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: face
  import: face

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-gpep517

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mahmoud/face
      tag: v${{package.version}}
      expected-commit: 6c8b1070312683cca0ed723f1cb99a7307f5ee91

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-boltons
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
    - uses: python/import
      with:
        imports: |
          from face import Command, echo

update:
  enabled: true
  github:
    identifier: mahmoud/face
    strip-prefix: v
    use-tag: true
