package:
  name: py3-django
  version: 5.1.2
  epoch: 0
  description: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-asgiref
      - py3-sqlparse
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c499184f198df8deb8b5f7282b679babef8384ff
      repository: https://github.com/django/django
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - (.*)(a|b|rc)(.*) # Ignore alpha, beta, and rc releases
  github:
    identifier: django/django
    use-tag: true

test:
  pipeline:
    - runs: |
        python3 ./test.py > output.out 2>&1
        grep -E "ERROR|None" output.out && exit 1
        django-admin --version
        django-admin --help
