package:
  name: py3-tinycss2
  version: 1.3.0
  epoch: 2
  description: A tiny CSS parser
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tinycss2
  import: tinycss2

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-flit-core

pipeline:
  - uses: fetch
    with:
      expected-sha256: 152f9acabd296a8375fbca5b84c961ff95971fcfc32e79550c8df8e29118c54d
      uri: https://files.pythonhosted.org/packages/source/t/tinycss2/tinycss2-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-webencodings
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  release-monitor:
    identifier: 16655
