package:
  name: py3-sacrebleu
  version: 2.4.2
  epoch: 1
  description: Reference BLEU implementation that auto-downloads test sets and reports a version string to facilitate cross-lab comparisons
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - numpy
      - py3-colorama
      - py3-lxml
      - py3-portalocker
      - py3-regex
      - py3-tabulate
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mjpost/sacrebleu
      expected-commit: 908ce509a0bfc2c993f515e45be4159fc8363ee2
      tag: v${{package.version}}

  - runs: |
      # get_long_description() does not work as expected with 'python/build-wheel' since
      # it couldn't find the `CHANGELOG.md` in the current directory. So disable this NIT func.
      sed -i -e '/long_description=get_long_description(),/d' setup.py

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: mjpost/sacrebleu
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        sacrebleu --version
        sacrebleu --help
