package:
  name: py3-cairo
  version: 1.27.0
  epoch: 0
  description: Python3 bindings for the cairo graphics library
  copyright:
    - license: LGPL-2.0-or-later
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cmake
      - expat-dev
      - fontconfig-dev
      - freetype-dev
      - libpng-dev
      - meson
      - openssf-compiler-options
      - python3-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pygobject/pycairo
      expected-commit: 0a5d483cb636beb678f78287a5e0095222d47988
      tag: v${{package.version}}

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true

  - uses: meson/compile

  - uses: meson/install

  - runs: python3 -m compileall "${{targets.destdir}}"/usr/lib

  - uses: strip

subpackages:
  - name: py3-cairo-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - py3-cairo
    description: py3-cairo dev

update:
  enabled: true
  github:
    identifier: pygobject/pycairo
    strip-prefix: v
