package:
  name: py3-tzlocal
  version: '5.2'
  epoch: 1
  description: tzinfo object for the local timezone
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tzlocal
  import: tzlocal

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8d399205578f1a9342816409cc1e46a93ebd5755e39ea2d85334bea911bf0e6e
      uri: https://files.pythonhosted.org/packages/source/t/tzlocal/tzlocal-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-tzdata
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
    - uses: py/one-python
      with:
        content: |
          cat <<'EOF' >> /tmp/test.py
          from tzlocal import get_localzone
          tz = get_localzone()
          tz
          EOF
          python3 /tmp/test.py

update:
  enabled: true
  github:
    identifier: regebro/tzlocal
    use-tag: true
