package:
  name: py3-pyfarmhash
  version: 0.3.2
  epoch: 4
  description: Google FarmHash Bindings for Python
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pyfarmhash
  import: no-valid-import

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '300'

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4146308a0ed0b37d69003199c90fa59b155666c9deb0249b40e594cee10551ea
      uri: https://files.pythonhosted.org/packages/source/p/pyfarmhash/pyfarmhash-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: false
  manual: true
  exclude-reason: no releases, tags, and release-monitor id
