package:
  name: py3-isort
  version: 5.13.2
  epoch: 1
  description: A Python utility / library to sort imports.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PyCQA/isort
      tag: ${{package.version}}
      expected-commit: c655831799765e9593989ee12faba13b6ca391a5

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: PyCQA/isort

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: python/import
      with:
        import: isort
      runs: |
        isort --version
        isort --help
        isort-identify-imports version
        isort-identify-imports --help
