package:
  name: py3-ml-metadata
  version: 1.16.0
  epoch: 0
  description: For recording and retrieving metadata associated with ML developer and data scientist workflows.
  copyright:
    - license: MIT
  resources:
    cpu: 14
    memory: 50Gi
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - bash
      - bazel-6
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc~13
      - openjdk-11
      - openssl-dev
      - patch
      - py3-setuptools
      - python3-dev
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    BAZEL_CXXOPTS: -std=c++17:-w

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/ml-metadata
      tag: v${{package.version}}
      expected-commit: d694290634c55742d772f01e12f63ab5b7d2c392

  - uses: patch
    with:
      series: series

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --skip-build --root="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: ml-metadata-store-server
    description: ML Metadata remote gRPC server
    pipeline:
      - runs: |
          # Reduce the number of jobs to avoid OOM
          bazel build -c opt --define grpc_no_ares=true --jobs $(($(grep -c ^processor /proc/cpuinfo) / 2)) //ml_metadata/metadata_store:metadata_store_server

          mkdir -p "${{targets.contextdir}}/usr/bin"
          cp bazel-bin/ml_metadata/metadata_store/metadata_store_server "${{targets.contextdir}}/usr/bin"
      - uses: strip
    test:
      pipeline:
        - runs: |
            metadata_store_server --version

update:
  enabled: true
  github:
    identifier: google/ml-metadata
    use-tag: true
    strip-prefix: v
