package:
  name: ruby-3.2
  version: 3.2.5
  epoch: 1
  description: "the Ruby programming language"
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    provides:
      - ruby=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - bison
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - oniguruma-dev
      - openssl-dev
      - readline-dev
      - ruby-3.1
      - rust
      - sqlite-dev
      - xz-dev
      - yaml-dev
      - zlib-dev

vars:
  prefix: /usr

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: underscore-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ruby/ruby
      tag: v${{vars.underscore-package-version}}
      expected-commit: 31d0f1a2e7dbfb60731d1f05b868e1d578cda493

  - name: Generate and Configure
    runs: |
      ./autogen.sh
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=${{vars.prefix}} \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --enable-yjit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |-
      # Ignore the patch version of ruby since ruby will install under the
      # version of the latest standard library. Should produce the string 3.2.*
      RUBYWILD="$(echo ${{package.version}} | cut -d. -f-2).*"

      RUBYDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/$RUBYWILD
      rm -rf ${RUBYDIR}/bundler
      rm ${RUBYDIR}/bundler.rb

      GEMDIR=${{targets.destdir}}${{vars.prefix}}/lib/ruby/gems/$RUBYWILD
      rm -rf ${GEMDIR}/gems/bundler-*
      rm ${GEMDIR}/specifications/default/bundler-*.gemspec

      rm ${{targets.destdir}}/usr/bin/bundle \
         ${{targets.destdir}}/usr/bin/bundler

subpackages:
  - name: "ruby-3.2-doc"
    description: "ruby documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/ri "${{targets.subpkgdir}}"/usr/share/

  - name: "ruby-3.2-dev"
    description: "ruby development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  version-transform:
    - match: "_"
      replace: .
  github:
    identifier: ruby/ruby
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v3_2_

test:
  pipeline:
    - runs: |
        ruby --version | grep ${{package.version}}

        cat <<EOF >> /tmp/hello.rb
        puts("Hello Wolfi!")
        EOF

        ruby /tmp/hello.rb
