package:
  name: rustup
  version: 1.27.1
  epoch: 2
  description: "rustup is an installer for the systems programming language Rust"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - git
      - libLLVM-15
      - make
      - openssl-dev
      - python3
      - rust
      - wolfi-base

pipeline:
  # There's some autodetection in the build that requires it to run from a git repository.
  - uses: git-checkout
    with:
      repository: https://github.com/rust-lang/rustup.git
      tag: ${{package.version}}
      expected-commit: 54dd3d00fd20e64dc522517a0d7be4285570a2f1

  - name: Configure and build
    runs: |
      cargo auditable build --release --features no-self-update --bin rustup-init
      install -d "${{targets.destdir}}"/usr/bin
      install -m755 target/release/rustup-init "${{targets.destdir}}"/usr/bin/
      ln -s /usr/bin/rustup-init "${{targets.destdir}}"/usr/bin/rustup

  - uses: strip

update:
  enabled: true
  github:
    identifier: rust-lang/rustup
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        rustup --version
        rustup-init --version
        rustup --help
        rustup-init --help
