package:
  name: systemd
  version: "256.7"
  epoch: 0
  description: The systemd System and Service Manager
  copyright:
    - license: LGPL-2.1-or-later AND GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox-full
      - ca-certificates-bundle
      - clang-16
      - cmake
      - coreutils
      - gperf
      - kmod-dev
      - libbpf
      - libcap-dev
      - libmount
      - libuuid
      - llvm16
      - meson
      - ninja
      - openssf-compiler-options
      - posix-libc-utils
      - py3-jinja2
      - py3-pyelftools
      - python3
      - util-linux-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/systemd/systemd
      tag: v${{package.version}}
      expected-commit: 7635d01869ba325b9cf450923c8f13912b7ca536

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - runs: |
      mkdir -p ${{targets.destdir}}/lib
      mv ${{targets.destdir}}/usr/lib/libsystemd.so* ${{targets.destdir}}/lib/

subpackages:
  - name: "systemd-dev"
    description: "headers for systemd"
    pipeline:
      - uses: split/dev

  - name: "libsystemd"
    description: "systemd library"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/lib
          mv ${{targets.destdir}}/lib/libsystemd.so.* ${{targets.subpkgdir}}/lib

  - name: "libsystemd-shared"
    description: "systemd library"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          cp ${{targets.destdir}}/usr/lib/systemd/libsystemd-shared-*.so  ${{targets.subpkgdir}}/usr/lib/

  - name: "systemd-boot"
    description: "systemd bootloader"
    dependencies:
      runtime:
        - libsystemd-shared
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/kernel/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/systemd/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/systemd/system-generators/
          cp -r ${{targets.destdir}}/etc/kernel ${{targets.subpkgdir}}/etc/
          cp -r ${{targets.destdir}}/usr/bin/kernel-install ${{targets.subpkgdir}}/usr/bin/
          cp -r ${{targets.destdir}}/usr/bin/bootctl ${{targets.subpkgdir}}/usr/bin/
          cp -r ${{targets.destdir}}/usr/lib/kernel ${{targets.subpkgdir}}/usr/lib/
          cp -r ${{targets.destdir}}/usr/lib/systemd/boot ${{targets.subpkgdir}}/usr/lib/systemd/
          cp -r ${{targets.destdir}}/usr/lib/systemd/systemd-bless-boot ${{targets.subpkgdir}}/usr/lib/systemd/
          cp -r ${{targets.destdir}}/usr/lib/systemd/system-generators/systemd-bless-boot-generator ${{targets.subpkgdir}}/usr/lib/systemd/system-generators/
    test:
      pipeline:
        - runs: |
            bootctl --version
            bootctl --help
            kernel-install --version
            kernel-install --help

  - name: "systemd-init"
    description: "Configure systemd for use as an init system"
    dependencies:
      runtime:
        - ${{package.name}}
        - tzdata
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc
          ln -s /usr/lib/systemd/systemd ${{targets.subpkgdir}}/init
          ln -sf /usr/share/zoneinfo/UTC ${{targets.subpkgdir}}/etc/localtime

update:
  enabled: true
  github:
    identifier: systemd/systemd
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - build-base
        - systemd-dev
        - libsystemd
  pipeline:
    - name: "Check systemctl version"
      runs: |
        systemctl --version
        bootctl --version
        bootctl --help
        busctl --version
        busctl --help
        coredumpctl --version
        coredumpctl --help
        hostnamectl --version
        hostnamectl --help
        journalctl --version
        journalctl --help
        localectl --version
        localectl --help
        loginctl --version
        loginctl --help
        machinectl --version
        machinectl --help
        networkctl --version
        networkctl --help
        oomctl --version
        oomctl --help
        portablectl --version
        portablectl --help
        resolvectl --version
        resolvectl --help
        run0 --version
        run0 --help
        systemctl --help
        systemd-ac-power --version
        systemd-ac-power --help
        systemd-analyze --help
        systemd-ask-password --version
        systemd-ask-password --help
        systemd-cat --version
        systemd-cat --help
        systemd-cgls --version
        systemd-cgls --help
        systemd-cgtop --version
        systemd-cgtop --help
        systemd-confext --version
        systemd-confext --help
        systemd-creds --version
        systemd-creds --help
        systemd-delta --version
        systemd-delta --help
        systemd-detect-virt --help
        systemd-dissect --version
        systemd-dissect --help
        systemd-escape --version
        systemd-escape --help
        systemd-firstboot --version
        systemd-firstboot --help
        systemd-hwdb --version
        systemd-hwdb --help
        systemd-id128 --version
        systemd-id128 --help
        systemd-inhibit --version
        systemd-inhibit --help
        systemd-machine-id-setup --version
        systemd-machine-id-setup --help
        systemd-mount --version
        systemd-mount --help
        systemd-notify --version
        systemd-notify --help
        systemd-nspawn --version
        systemd-nspawn --help
        systemd-path --version
        systemd-path --help
        systemd-repart --version
        systemd-repart --help
        systemd-resolve --version
        systemd-resolve --help
        systemd-run --version
        systemd-run --help
        systemd-socket-activate --version
        systemd-socket-activate --help
        systemd-stdio-bridge --version
        systemd-stdio-bridge --help
        systemd-sysext --version
        systemd-sysext --help
        systemd-sysusers --version
        systemd-sysusers --help
        systemd-tmpfiles --version
        systemd-tmpfiles --help
        systemd-tty-ask-password-agent --version
        systemd-tty-ask-password-agent --help
        systemd-umount --version
        systemd-umount --help
        systemd-vmspawn --version
        systemd-vmspawn --help
        systemd-vpick --version
        systemd-vpick --help
        timedatectl --version
        timedatectl --help
        udevadm --help
        userdbctl --version
        userdbctl --help
        varlinkctl --version
        varlinkctl --help
        halt --help
        init --help
        poweroff --help
        reboot --help
        resolvconf --version
        resolvconf --help
        runlevel --help
        shutdown --help
        telinit --help
    - name: "Verify key binaries"
      runs: |
        systemctl --version
        systemd-analyze --version
        udevadm --version
        systemd-detect-virt --version
    - name: "Check libsystemd"
      runs: |
        ldconfig -p | grep libsystemd.so
        echo '#include <systemd/sd-bus.h>
        int main() { sd_bus *bus; return sd_bus_default_system(&bus); }' > test.c
        cc test.c -lsystemd -o test_systemd
        rm test.c test_systemd
