package:
  name: terragrunt
  version: 0.68.0
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - mockery

pipeline:
  - uses: git-checkout
    with:
      expected-commit: afd5d7f962bd1e651f04a44968342ed1642a8e8e
      repository: https://github.com/gruntwork-io/terragrunt
      tag: v${{package.version}}

  - runs: go generate ./...

  - uses: go/bump
    with:
      deps: github.com/anchore/archiver/v3@v3.5.2
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2

  - uses: go/build
    with:
      output: terragrunt
      packages: .
      ldflags: "-X  github.com/gruntwork-io/go-commons/version.Version=v${{package.version}}"

  - uses: strip

test:
  pipeline:
    - name: Verify terragrunt
      runs: |
        set -o pipefail
        terragrunt --version
        terragrunt --help

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
