package:
  name: traefik-3.1
  version: 3.1.6
  epoch: 0
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT
  dependencies:
    provides:
      - traefik=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - nodejs-20
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4613ddd757acf09f0d47fa8ce82bea670ede82de
      repository: https://github.com/traefik/traefik
      tag: v${{package.version}}

  - working-directory: webui
    runs: |
      yarn install
      yarn build

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/traefik
      output: traefik
      ldflags: |
        -X github.com/traefik/traefik/v3/pkg/version.Version=${{package.version}}
        -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
        -X github.com/traefik/traefik/v3/pkg/version.Codename=$CODENAME

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
    tag-filter: v3.1.

test:
  pipeline:
    - runs: |
        set -o pipefail
        traefik version | grep ${{package.version}}
        traefik --help
