package:
  name: tree-sitter
  version: 0.24.3
  epoch: 0
  description: "Incremental parsing system for programming tools"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tree-sitter/tree-sitter
      tag: v${{package.version}}
      expected-commit: bdfe32402e85673bbc693216f0a6ef72c98bb665

  - uses: autoconf/make

  - runs: |
      make install DESTDIR="${{targets.contextdir}}" PREFIX=/usr V=1

  - uses: strip

subpackages:
  - name: tree-sitter-dev
    pipeline:
      - uses: split/dev
    description: tree-sitter dev

update:
  enabled: true
  github:
    identifier: tree-sitter/tree-sitter
    strip-prefix: v
    tag-filter: v
