package:
  name: uv
  version: 0.4.20
  epoch: 0
  description: An extremely fast Python package installer and resolver, written in Rust.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - cmake
      - openssf-compiler-options
      - openssl-dev
      - perl
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/uv
      tag: ${{package.version}}
      expected-commit: 0e1b25a536b727276cd4012ce2e2751f9dac141d

  - runs: |
      cargo auditable build --locked --release
      install -Dm755 target/release/uv "${{targets.destdir}}"/usr/bin/uv
      install -Dm755 target/release/uvx "${{targets.destdir}}"/usr/bin/uvx

  - uses: strip

update:
  enabled: true
  github:
    identifier: astral-sh/uv

test:
  pipeline:
    - runs: |
        uv --version | grep ${{package.version}}
        uvx --version | grep ${{package.version}}
        uv --help
        uvx --help
