name: Wolfictl Lint

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

permissions:
  contents: read

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    # this need to point to main to always get the latest action
    - uses: wolfi-dev/actions/wolfictl-lint@main # main
